// src/services/ShippingService.ts
export interface ShippingCalculation {
  method: string;
  price: number;
  estimatedDays: string;
  isAvailable: boolean;
}

export interface PackageInfo {
  size: 'S' | 'M' | 'L';
  weight: number;
  dimensions: {
    length: number;
    width: number;
    height: number;
  };
}

export class ShippingService {
  static calculateShipping(
    country: string,
    state: string,
    orderTotal: number,
    packageInfo: PackageInfo
  ): ShippingCalculation[] {
    const results: ShippingCalculation[] = [];

    // US Domestic (excluding Alaska & Hawaii)
    if (country === 'US' && !['AK', 'HI'].includes(state)) {
      if (orderTotal >= 50) {
        results.push({
          method: 'us_free',
          price: 0,
          estimatedDays: '5-7 business days',
          isAvailable: true
        });
      } else {
        results.push({
          method: 'us_standard',
          price: 9.99,
          estimatedDays: '5-7 business days',
          isAvailable: true
        });
      }
    }

    // US Territories (Alaska & Hawaii)
    if (country === 'US' && ['AK', 'HI'].includes(state)) {
      const territoryPricing = {
        'S': 30,
        'M': 50,
        'L': 150
      };

      results.push({
        method: `us_territories_${packageInfo.size.toLowerCase()}`,
        price: territoryPricing[packageInfo.size],
        estimatedDays: '7-10 business days',
        isAvailable: true
      });
    }

    // Canada
    if (country === 'CA') {
      const canadaPricing = {
        'S': 35,
        'M': 100,
        'L': 200
      };

      results.push({
        method: `canada_${packageInfo.size.toLowerCase()}`,
        price: canadaPricing[packageInfo.size],
        estimatedDays: '7-14 business days',
        isAvailable: true
      });
    }

    // International (requires quote)
    if (!['US', 'CA'].includes(country)) {
      results.push({
        method: 'international_quote',
        price: 0,
        estimatedDays: 'Contact for quote',
        isAvailable: true
      });
    }

    return results;
  }

  static determinePackageSize(items: any[]): PackageInfo {
    // Logic to determine package size based on cart items
    // This would analyze product dimensions and weights
    // For now, return a default medium package
    return {
      size: 'M',
      weight: 15.0,
      dimensions: {
        length: 18,
        width: 12,
        height: 6
      }
    };
  }

  static getCountryName(countryCode: string): string {
    const countries: { [key: string]: string } = {
      'US': 'United States',
      'CA': 'Canada',
      'GB': 'United Kingdom',
      'DE': 'Germany',
      'FR': 'France',
      'AU': 'Australia',
      'JP': 'Japan',
      'IT': 'Italy',
      'ES': 'Spain',
      'NL': 'Netherlands',
      'BE': 'Belgium',
      'CH': 'Switzerland',
      'AT': 'Austria',
      'SE': 'Sweden',
      'NO': 'Norway',
      'DK': 'Denmark',
      'FI': 'Finland',
      'PL': 'Poland',
      'CZ': 'Czech Republic',
      'HU': 'Hungary',
      'PT': 'Portugal',
      'IE': 'Ireland',
      'LU': 'Luxembourg',
      'GR': 'Greece',
      'CY': 'Cyprus',
      'MT': 'Malta',
      'SI': 'Slovenia',
      'SK': 'Slovakia',
      'EE': 'Estonia',
      'LV': 'Latvia',
      'LT': 'Lithuania',
      'BG': 'Bulgaria',
      'RO': 'Romania',
      'HR': 'Croatia',
      'RS': 'Serbia',
      'BA': 'Bosnia and Herzegovina',
      'MK': 'North Macedonia',
      'AL': 'Albania',
      'ME': 'Montenegro',
      'XK': 'Kosovo',
      'MD': 'Moldova',
      'UA': 'Ukraine',
      'BY': 'Belarus',
      'RU': 'Russia',
      'TR': 'Turkey',
      'IL': 'Israel',
      'AE': 'United Arab Emirates',
      'SA': 'Saudi Arabia',
      'EG': 'Egypt',
      'ZA': 'South Africa',
      'NG': 'Nigeria',
      'KE': 'Kenya',
      'GH': 'Ghana',
      'MA': 'Morocco',
      'TN': 'Tunisia',
      'DZ': 'Algeria',
      'LY': 'Libya',
      'SD': 'Sudan',
      'ET': 'Ethiopia',
      'UG': 'Uganda',
      'TZ': 'Tanzania',
      'ZW': 'Zimbabwe',
      'BW': 'Botswana',
      'NA': 'Namibia',
      'ZM': 'Zambia',
      'MW': 'Malawi',
      'MZ': 'Mozambique',
      'MG': 'Madagascar',
      'MU': 'Mauritius',
      'SC': 'Seychelles',
      'RE': 'Réunion',
      'YT': 'Mayotte',
      'KM': 'Comoros',
      'DJ': 'Djibouti',
      'SO': 'Somalia',
      'ER': 'Eritrea',
      'SS': 'South Sudan',
      'CF': 'Central African Republic',
      'TD': 'Chad',
      'NE': 'Niger',
      'ML': 'Mali',
      'BF': 'Burkina Faso',
      'SN': 'Senegal',
      'GM': 'Gambia',
      'GW': 'Guinea-Bissau',
      'GN': 'Guinea',
      'SL': 'Sierra Leone',
      'LR': 'Liberia',
      'CI': 'Ivory Coast',
      'GH': 'Ghana',
      'TG': 'Togo',
      'BJ': 'Benin',
      'NG': 'Nigeria',
      'CM': 'Cameroon',
      'GQ': 'Equatorial Guinea',
      'GA': 'Gabon',
      'CG': 'Republic of the Congo',
      'CD': 'Democratic Republic of the Congo',
      'AO': 'Angola',
      'ST': 'São Tomé and Príncipe',
      'CV': 'Cape Verde',
      'MR': 'Mauritania',
      'MA': 'Morocco',
      'DZ': 'Algeria',
      'TN': 'Tunisia',
      'LY': 'Libya',
      'EG': 'Egypt',
      'SD': 'Sudan',
      'SS': 'South Sudan',
      'ET': 'Ethiopia',
      'ER': 'Eritrea',
      'DJ': 'Djibouti',
      'SO': 'Somalia',
      'KE': 'Kenya',
      'UG': 'Uganda',
      'TZ': 'Tanzania',
      'RW': 'Rwanda',
      'BI': 'Burundi',
      'MW': 'Malawi',
      'ZM': 'Zambia',
      'ZW': 'Zimbabwe',
      'BW': 'Botswana',
      'NA': 'Namibia',
      'ZA': 'South Africa',
      'LS': 'Lesotho',
      'SZ': 'Eswatini',
      'MZ': 'Mozambique',
      'MG': 'Madagascar',
      'MU': 'Mauritius',
      'SC': 'Seychelles',
      'KM': 'Comoros',
      'YT': 'Mayotte',
      'RE': 'Réunion',
      'MV': 'Maldives',
      'LK': 'Sri Lanka',
      'IN': 'India',
      'BD': 'Bangladesh',
      'BT': 'Bhutan',
      'NP': 'Nepal',
      'PK': 'Pakistan',
      'AF': 'Afghanistan',
      'IR': 'Iran',
      'IQ': 'Iraq',
      'SY': 'Syria',
      'LB': 'Lebanon',
      'JO': 'Jordan',
      'PS': 'Palestine',
      'IL': 'Israel',
      'SA': 'Saudi Arabia',
      'YE': 'Yemen',
      'OM': 'Oman',
      'AE': 'United Arab Emirates',
      'QA': 'Qatar',
      'BH': 'Bahrain',
      'KW': 'Kuwait',
      'IQ': 'Iraq',
      'IR': 'Iran',
      'AF': 'Afghanistan',
      'PK': 'Pakistan',
      'IN': 'India',
      'BD': 'Bangladesh',
      'BT': 'Bhutan',
      'NP': 'Nepal',
      'LK': 'Sri Lanka',
      'MV': 'Maldives',
      'MM': 'Myanmar',
      'TH': 'Thailand',
      'LA': 'Laos',
      'KH': 'Cambodia',
      'VN': 'Vietnam',
      'MY': 'Malaysia',
      'SG': 'Singapore',
      'BN': 'Brunei',
      'ID': 'Indonesia',
      'PH': 'Philippines',
      'TL': 'East Timor',
      'PG': 'Papua New Guinea',
      'FJ': 'Fiji',
      'VU': 'Vanuatu',
      'SB': 'Solomon Islands',
      'NC': 'New Caledonia',
      'PF': 'French Polynesia',
      'WS': 'Samoa',
      'TO': 'Tonga',
      'KI': 'Kiribati',
      'TV': 'Tuvalu',
      'NR': 'Nauru',
      'PW': 'Palau',
      'FM': 'Micronesia',
      'MH': 'Marshall Islands',
      'CK': 'Cook Islands',
      'NU': 'Niue',
      'TK': 'Tokelau',
      'AS': 'American Samoa',
      'GU': 'Guam',
      'MP': 'Northern Mariana Islands',
      'VI': 'U.S. Virgin Islands',
      'PR': 'Puerto Rico',
      'DO': 'Dominican Republic',
      'HT': 'Haiti',
      'JM': 'Jamaica',
      'CU': 'Cuba',
      'BS': 'Bahamas',
      'BB': 'Barbados',
      'AG': 'Antigua and Barbuda',
      'DM': 'Dominica',
      'GD': 'Grenada',
      'KN': 'Saint Kitts and Nevis',
      'LC': 'Saint Lucia',
      'VC': 'Saint Vincent and the Grenadines',
      'TT': 'Trinidad and Tobago',
      'BZ': 'Belize',
      'GT': 'Guatemala',
      'SV': 'El Salvador',
      'HN': 'Honduras',
      'NI': 'Nicaragua',
      'CR': 'Costa Rica',
      'PA': 'Panama',
      'MX': 'Mexico',
      'US': 'United States',
      'CA': 'Canada',
      'GL': 'Greenland',
      'IS': 'Iceland',
      'FO': 'Faroe Islands',
      'SJ': 'Svalbard and Jan Mayen',
      'NO': 'Norway',
      'SE': 'Sweden',
      'FI': 'Finland',
      'DK': 'Denmark',
      'EE': 'Estonia',
      'LV': 'Latvia',
      'LT': 'Lithuania',
      'PL': 'Poland',
      'DE': 'Germany',
      'NL': 'Netherlands',
      'BE': 'Belgium',
      'LU': 'Luxembourg',
      'FR': 'France',
      'CH': 'Switzerland',
      'AT': 'Austria',
      'LI': 'Liechtenstein',
      'IT': 'Italy',
      'SM': 'San Marino',
      'VA': 'Vatican City',
      'MT': 'Malta',
      'ES': 'Spain',
      'AD': 'Andorra',
      'MC': 'Monaco',
      'PT': 'Portugal',
      'IE': 'Ireland',
      'GB': 'United Kingdom',
      'IM': 'Isle of Man',
      'JE': 'Jersey',
      'GG': 'Guernsey',
      'CY': 'Cyprus',
      'GR': 'Greece',
      'TR': 'Turkey',
      'BG': 'Bulgaria',
      'RO': 'Romania',
      'MD': 'Moldova',
      'UA': 'Ukraine',
      'BY': 'Belarus',
      'RU': 'Russia',
      'GE': 'Georgia',
      'AM': 'Armenia',
      'AZ': 'Azerbaijan',
      'KZ': 'Kazakhstan',
      'UZ': 'Uzbekistan',
      'TM': 'Turkmenistan',
      'TJ': 'Tajikistan',
      'KG': 'Kyrgyzstan',
      'MN': 'Mongolia',
      'CN': 'China',
      'TW': 'Taiwan',
      'HK': 'Hong Kong',
      'MO': 'Macau',
      'KP': 'North Korea',
      'KR': 'South Korea',
      'JP': 'Japan',
      'RU': 'Russia',
      'KZ': 'Kazakhstan',
      'UZ': 'Uzbekistan',
      'TM': 'Turkmenistan',
      'TJ': 'Tajikistan',
      'KG': 'Kyrgyzstan',
      'AF': 'Afghanistan',
      'PK': 'Pakistan',
      'IN': 'India',
      'BD': 'Bangladesh',
      'BT': 'Bhutan',
      'NP': 'Nepal',
      'LK': 'Sri Lanka',
      'MV': 'Maldives',
      'MM': 'Myanmar',
      'TH': 'Thailand',
      'LA': 'Laos',
      'KH': 'Cambodia',
      'VN': 'Vietnam',
      'MY': 'Malaysia',
      'SG': 'Singapore',
      'BN': 'Brunei',
      'ID': 'Indonesia',
      'PH': 'Philippines',
      'TL': 'East Timor',
      'PG': 'Papua New Guinea',
      'AU': 'Australia',
      'NZ': 'New Zealand',
      'FJ': 'Fiji',
      'VU': 'Vanuatu',
      'SB': 'Solomon Islands',
      'NC': 'New Caledonia',
      'PF': 'French Polynesia',
      'WS': 'Samoa',
      'TO': 'Tonga',
      'KI': 'Kiribati',
      'TV': 'Tuvalu',
      'NR': 'Nauru',
      'PW': 'Palau',
      'FM': 'Micronesia',
      'MH': 'Marshall Islands',
      'CK': 'Cook Islands',
      'NU': 'Niue',
      'TK': 'Tokelau',
      'AS': 'American Samoa',
      'GU': 'Guam',
      'MP': 'Northern Mariana Islands',
      'VI': 'U.S. Virgin Islands',
      'PR': 'Puerto Rico',
      'DO': 'Dominican Republic',
      'HT': 'Haiti',
      'JM': 'Jamaica',
      'CU': 'Cuba',
      'BS': 'Bahamas',
      'BB': 'Barbados',
      'AG': 'Antigua and Barbuda',
      'DM': 'Dominica',
      'GD': 'Grenada',
      'KN': 'Saint Kitts and Nevis',
      'LC': 'Saint Lucia',
      'VC': 'Saint Vincent and the Grenadines',
      'TT': 'Trinidad and Tobago',
      'BZ': 'Belize',
      'GT': 'Guatemala',
      'SV': 'El Salvador',
      'HN': 'Honduras',
      'NI': 'Nicaragua',
      'CR': 'Costa Rica',
      'PA': 'Panama',
      'MX': 'Mexico',
      'US': 'United States',
      'CA': 'Canada',
      'GL': 'Greenland',
      'IS': 'Iceland',
      'FO': 'Faroe Islands',
      'SJ': 'Svalbard and Jan Mayen',
      'NO': 'Norway',
      'SE': 'Sweden',
      'FI': 'Finland',
      'DK': 'Denmark',
      'EE': 'Estonia',
      'LV': 'Latvia',
      'LT': 'Lithuania',
      'PL': 'Poland',
      'DE': 'Germany',
      'NL': 'Netherlands',
      'BE': 'Belgium',
      'LU': 'Luxembourg',
      'FR': 'France',
      'CH': 'Switzerland',
      'AT': 'Austria',
      'LI': 'Liechtenstein',
      'IT': 'Italy',
      'SM': 'San Marino',
      'VA': 'Vatican City',
      'MT': 'Malta',
      'ES': 'Spain',
      'AD': 'Andorra',
      'MC': 'Monaco',
      'PT': 'Portugal',
      'IE': 'Ireland',
      'GB': 'United Kingdom',
      'IM': 'Isle of Man',
      'JE': 'Jersey',
      'GG': 'Guernsey',
      'CY': 'Cyprus',
      'GR': 'Greece',
      'TR': 'Turkey',
      'BG': 'Bulgaria',
      'RO': 'Romania',
      'MD': 'Moldova',
      'UA': 'Ukraine',
      'BY': 'Belarus',
      'RU': 'Russia',
      'GE': 'Georgia',
      'AM': 'Armenia',
      'AZ': 'Azerbaijan',
      'KZ': 'Kazakhstan',
      'UZ': 'Uzbekistan',
      'TM': 'Turkmenistan',
      'TJ': 'Tajikistan',
      'KG': 'Kyrgyzstan',
      'MN': 'Mongolia',
      'CN': 'China',
      'TW': 'Taiwan',
      'HK': 'Hong Kong',
      'MO': 'Macau',
      'KP': 'North Korea',
      'KR': 'South Korea',
      'JP': 'Japan'
    };

    return countries[countryCode] || countryCode;
  }
}
